-- Import av StFF:s föreningslista för Stockholm.
-- Källa: https://www.stff.se/forening/vara-foreningar/
-- Genererad: 2026-08-06
-- Antal föreningar: 367

begin;

insert into public.clubs (name, region, municipality, website, verified)
values
  ('A C Camelen', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/a-c-camelen/10876/', true),
  ('AC Azzurri', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ac-azzurri/9040/', true),
  ('AC Sundbyberg', 'Stockholm', 'Sundbyberg', 'https://www.stff.se/rs/foreningar/ac-sundbyberg--/13453/', true),
  ('AFC Hemmesta', 'Stockholm', 'Värmdö', 'https://www.stff.se/rs/foreningar/afc-hemmesta/13696/', true),
  ('AIK FF', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/aik-ff/6864/', true),
  ('AIK Fotboll AB', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/aik-fotboll-ab/6413/', true),
  ('AIK Framtid FK', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/aik-framtid-fk/11817/', true),
  ('AK Stockholmsatleterna', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ak-stockholmsatleterna-/7445/', true),
  ('Aktiva Juniorer IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/aktiva-juniorer-if/12551/', true),
  ('All Stars FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/all-stars-ff/13578/', true),
  ('All Stripes SC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/all-stripes-sc/11830/', true),
  ('Alvik FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/alvik-fc/13220/', true),
  ('Anatolia IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/anatolia-if/13665/', true),
  ('Apollon Solna FK', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/apollon-solna-fk/12027/', true),
  ('Arameisk-Syrianska IF', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/arameisk-syrianska-if/12194/', true),
  ('Argentinska Stockholm IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/argentinska-stockholm-if/13382/', true),
  ('AS Maria', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/as-maria-/14723/', true),
  ('AS Solna FF', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/as-solna-ff/13537/', true),
  ('Aspuddens FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/aspuddens-ff/12688/', true),
  ('Assyriska Botkyrka SK', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/assyriska-botkyrka-sk/13583/', true),
  ('Assyriska FF Babylon', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/assyriska-ff-babylon/7071/', true),
  ('Assyriska KF Botkyrka', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/assyriska-kf-botkyrka/9043/', true),
  ('Astra FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/astra-fc/13653/', true),
  ('Athletic FC Järfälla', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/athletic-fc-jarfalla-/13209/', true),
  ('Atletic Blåsut FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/atletic-blasut-fc/13186/', true),
  ('AZ Milan SC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/az-milan-sc/13614/', true),
  ('Bagarmossen Kärrtorp BK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bagarmossen-karrtorp-bk/7205/', true),
  ('Ballers FC', 'Stockholm', 'Sundbyberg', 'https://www.stff.se/rs/foreningar/ballers-fc-/13663/', true),
  ('Bamyan FF', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/bamyan-ff/14828/', true),
  ('Banjul FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/banjul-fc/13082/', true),
  ('Bele Barkarby FF', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/bele-barkarby-ff/11832/', true),
  ('Bellevue United FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bellevue-united-fc/13571/', true),
  ('Bemannia FC Stockholm', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bemannia-fc-stockholm/12612/', true),
  ('BK Bleket', 'Stockholm', 'Värmdö', 'https://www.stff.se/rs/foreningar/bk-bleket/9031/', true),
  ('BK Borsten', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bk-borsten/8135/', true),
  ('BK Buffalo', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bk-buffalo-/13515/', true),
  ('BK Bussenhus', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bk-bussenhus/13079/', true),
  ('BK Fyren', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bk-fyren/13180/', true),
  ('BK Fyren Ungdomsfotboll', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/bk-fyren-ungdomsfotboll-/13399/', true),
  ('BK Gömmaren', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/bk-gommaren/13048/', true),
  ('BK Hammarby', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bk-hammarby/13574/', true),
  ('BK Karlbergare', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bk-karlbergare/12187/', true),
  ('BK Träsket', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bk-trasket/8919/', true),
  ('BK Yardies', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bk-yardies/11835/', true),
  ('Bollmora Internacional IKF', 'Stockholm', 'Tyresö', 'https://www.stff.se/rs/foreningar/bollmora-internacional-ikf/11844/', true),
  ('Bollstanäs SK', 'Stockholm', 'Upplands Väsby', 'https://www.stff.se/rs/foreningar/bollstanas-sk/11544/', true),
  ('Bondegatans Bajare FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bondegatans-bajare-ff/6861/', true),
  ('Boo FF', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/boo-ff/9030/', true),
  ('Boo FK', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/boo-fk/8952/', true),
  ('Boo SK', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/boo-sk/11542/', true),
  ('Borussia Norr FC', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/borussia-norr-fc-/14783/', true),
  ('Botkyrka Academy FC', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/botkyrka-academy-fc-/13392/', true),
  ('Botkyrka Konya KUF', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/botkyrka-konya-kuf-/13610/', true),
  ('Botkyrkakurd FF', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/botkyrkakurd-ff/12426/', true),
  ('Bredden FC', 'Stockholm', 'Upplands Väsby', 'https://www.stff.se/rs/foreningar/bredden-fc-/13464/', true),
  ('Bro IK', 'Stockholm', 'Upplands-Bro', 'https://www.stff.se/rs/foreningar/bro-ik/11520/', true),
  ('Bromma TFF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bromma-tff/13525/', true),
  ('Brommapojkarna DFF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/brommapojkarna-dff/11685/', true),
  ('Bromstens IK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bromstens-ik/11517/', true),
  ('Bussenhus IK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/bussenhus-ik-/14738/', true),
  ('Bällsta FF', 'Stockholm', 'Vallentuna', 'https://www.stff.se/rs/foreningar/ballsta-ff/8487/', true),
  ('Camdja IKF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/camdja-ikf/12753/', true),
  ('Colo-Colo International FK', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/colo-colo-international-fk/13517/', true),
  ('Dalarö SK', 'Stockholm', 'Haninge', 'https://www.stff.se/rs/foreningar/dalaro-sk/11474/', true),
  ('Danderyd FF', 'Stockholm', 'Danderyd', 'https://www.stff.se/rs/foreningar/danderyd-ff/13714/', true),
  ('Danderyds SK FF', 'Stockholm', 'Danderyd', 'https://www.stff.se/rs/foreningar/danderyds-sk-ff/11467/', true),
  ('Danderyds SK FK', 'Stockholm', 'Danderyd', 'https://www.stff.se/rs/foreningar/danderyds-sk-fk-/13719/', true),
  ('Danderyds United FC', 'Stockholm', 'Danderyd', 'https://www.stff.se/rs/foreningar/danderyds-united-fc/13325/', true),
  ('Dardania Stockholm FF', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/dardania-stockholm-ff-/13269/', true),
  ('Djurgårdens Elitfotboll AB', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/djurgardens-elitfotboll-ab/12128/', true),
  ('Djurgårdens IF FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/djurgardens-if-ff/7897/', true),
  ('Djurgårdens TFF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/djurgardens-tff/13233/', true),
  ('Djurö-Vindö IF', 'Stockholm', 'Värmdö', 'https://www.stff.se/rs/foreningar/djuro-vindo-if/11452/', true),
  ('Drottningholms IS', 'Stockholm', 'Ekerö', 'https://www.stff.se/rs/foreningar/drottningholms-is/14775/', true),
  ('Edessa Syrianska KIF', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/edessa-syrianska-kif/12192/', true),
  ('Ekerö IK', 'Stockholm', 'Ekerö', 'https://www.stff.se/rs/foreningar/ekero-ik/11431/', true),
  ('Elite Stockholm FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/elite-stockholm-ff--/13651/', true),
  ('Enebybergs IF', 'Stockholm', 'Danderyd', 'https://www.stff.se/rs/foreningar/enebybergs-if/11421/', true),
  ('Enskede FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/enskede-ff/7216/', true),
  ('Enskede IK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/enskede-ik/11417/', true),
  ('Enskede United FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/enskede-united-fc/7773/', true),
  ('Erikslunds KF', 'Stockholm', 'Täby', 'https://www.stff.se/rs/foreningar/erikslunds-kf/11413/', true),
  ('Espanyol Academy IF', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/espanyol-academy-if/13150/', true),
  ('Essinge IK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/essinge-ik/11980/', true),
  ('Essinge Rovers IK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/essinge-rovers-ik-/13720/', true),
  ('Fairplay Futsal förening', 'Stockholm', null, 'https://www.stff.se/rs/foreningar/fairplay-futsal-forening-/14823/', true),
  ('FC Atletico Stockholm', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fc-atletico-stockholm-/13519/', true),
  ('FC Balingsnäs', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/fc-balingsnas-/13484/', true),
  ('FC Baloch', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fc-baloch/12755/', true),
  ('FC Björnligan', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fc-bjornligan/9034/', true),
  ('FC Brandbergen', 'Stockholm', 'Haninge', 'https://www.stff.se/rs/foreningar/fc-brandbergen/12847/', true),
  ('FC De barrio', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/fc-de-barrio-/14724/', true),
  ('FC Djursholm', 'Stockholm', 'Danderyd', 'https://www.stff.se/rs/foreningar/fc-djursholm/6787/', true),
  ('FC Drevviken', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/fc-drevviken-/14802/', true),
  ('FC Första', 'Stockholm', 'Nynäshamn', 'https://www.stff.se/rs/foreningar/fc-forsta-/13388/', true),
  ('FC Hagalund', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/fc-hagalund-/14759/', true),
  ('FC Järfälla', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/fc-jarfalla/10127/', true),
  ('FC Järvastaden', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/fc-jarvastaden-/13538/', true),
  ('FC Krukan', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fc-krukan/7832/', true),
  ('FC Kungsholmen', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fc-kungsholmen/13580/', true),
  ('FC Milano Stockholm', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/fc-milano-stockholm-/13442/', true),
  ('FC Moonlight', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/fc-moonlight-/14791/', true),
  ('FC Plavi Team Stockholm', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/fc-plavi-team-stockholm/7828/', true),
  ('FC Rotebro', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/fc-rotebro-/13516/', true),
  ('FC Rönninge', 'Stockholm', 'Salem', 'https://www.stff.se/rs/foreningar/fc-ronninge/13246/', true),
  ('FC Sampierdarenese', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fc-sampierdarenese/12583/', true),
  ('FC Segeltorp', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/fc-segeltorp/13502/', true),
  ('FC Solheim Täby', 'Stockholm', 'Täby', 'https://www.stff.se/rs/foreningar/fc-solheim-taby-/14777/', true),
  ('FC Sollentuna', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/fc-sollentuna-/13626/', true),
  ('FC Stockholm Internazionale', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fc-stockholm-internazionale/12338/', true),
  ('FC Stockholm Internazionale AB', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fc-stockholm-internazionale-ab/13302/', true),
  ('FC Stockholm Legends', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fc-stockholm-legends-/14827/', true),
  ('FC Söder', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fc-soder/12182/', true),
  ('FC Tolkarna', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fc-tolkarna/7035/', true),
  ('FC Tyresö United', 'Stockholm', 'Tyresö', 'https://www.stff.se/rs/foreningar/fc-tyreso-united/13087/', true),
  ('FC Ukrainska', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/fc-ukrainska/13398/', true),
  ('FC Väsby Akademiska', 'Stockholm', 'Upplands Väsby', 'https://www.stff.se/rs/foreningar/fc-vasby-akademiska-/13524/', true),
  ('FF Aura', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ff-aura-/13711/', true),
  ('Fisksätra IF', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/fisksatra-if/11377/', true),
  ('Fittja IF', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/fittja-if/7611/', true),
  ('FK Bosna 08', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fk-bosna-08/12646/', true),
  ('FK Bromma', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fk-bromma/9027/', true),
  ('Flemingsberg IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/flemingsberg-if/13116/', true),
  ('Flemingsberg United FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/flemingsberg-united-fc/13222/', true),
  ('FoC Farsta FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/foc-farsta-ff/13197/', true),
  ('Football Club Nord', 'Stockholm', 'Täby', 'https://www.stff.se/rs/foreningar/football-club-nord--/14786/', true),
  ('Fryshuset IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/fryshuset-if/13214/', true),
  ('Fullersta FK', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/fullersta-fk/11938/', true),
  ('Futsal Club Bosna', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/futsal-club-bosna/12954/', true),
  ('Föreningen Svenska Österbotten', 'Stockholm', 'Upplands Väsby', 'https://www.stff.se/rs/foreningar/foreningen-svenska-osterbotten/9740/', true),
  ('Gamla Skanstull BK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/gamla-skanstull-bk-/13457/', true),
  ('Gamla Stans IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/gamla-stans-if/10206/', true),
  ('Gimonäs FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/gimonas-fc/12316/', true),
  ('Grödinge SK', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/grodinge-sk/9008/', true),
  ('Gröndals FF', 'Stockholm', null, 'https://www.stff.se/rs/foreningar/grondals-ff/14726/', true),
  ('Gröndals IK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/grondals-ik/11254/', true),
  ('Gustavsbergs IF FK', 'Stockholm', 'Värmdö', 'https://www.stff.se/rs/foreningar/gustavsbergs-if-fk/11780/', true),
  ('Hagalunds IS', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/hagalunds-is/11210/', true),
  ('Hallunda IF', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/hallunda-if/13527/', true),
  ('Hammarby Fotboll AB', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/hammarby-fotboll-ab/6412/', true),
  ('Hammarby IF DFF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/hammarby-if-dff/7207/', true),
  ('Hammarby IF FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/hammarby-if-ff/7186/', true),
  ('Hammarby TFF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/hammarby-tff-/11346/', true),
  ('Hamnstaden IF', 'Stockholm', 'Nynäshamn', 'https://www.stff.se/rs/foreningar/hamnstaden-if-/14758/', true),
  ('Handelskamraternas IS', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/handelskamraternas-is/11802/', true),
  ('Haninge FF', 'Stockholm', 'Haninge', 'https://www.stff.se/rs/foreningar/haninge-ff/13083/', true),
  ('Haninge IF', 'Stockholm', 'Haninge', 'https://www.stff.se/rs/foreningar/haninge-if/11672/', true),
  ('Hanvikens SK', 'Stockholm', 'Tyresö', 'https://www.stff.se/rs/foreningar/hanvikens-sk/11182/', true),
  ('Huddinge IF', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/huddinge-if/11107/', true),
  ('Husby FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/husby-ff/12663/', true),
  ('Huvudsta Dragonz IF', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/huvudsta-dragonz-if-/13547/', true),
  ('Hägersten FC Stockholm', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/hagersten-fc-stockholm-/13231/', true),
  ('Hägersten SK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/hagersten-sk/11079/', true),
  ('Hässelby SK FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/hasselby-sk-ff/6899/', true),
  ('Högalids IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/hogalids-if/11053/', true),
  ('Högdalens AIS', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/hogdalens-ais/11050/', true),
  ('Iberoamericana IF', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/iberoamericana-if/6881/', true),
  ('IF Atletico Camelen', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/if-atletico-camelen/12365/', true),
  ('IF Brommapojkarna', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/if-brommapojkarna/9026/', true),
  ('IF Lokomotiv Blackeberg', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/if-lokomotiv-blackeberg/7325/', true),
  ('IF Olympia', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/if-olympia/8962/', true),
  ('IF Söderkamraterna', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/if-soderkamraterna/8925/', true),
  ('IF Wasa', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/if-wasa/12424/', true),
  ('IFK Aspudden-Tellus', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ifk-aspudden-tellus/11027/', true),
  ('IFK Bergshamra', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/ifk-bergshamra/11024/', true),
  ('IFK Haninge', 'Stockholm', 'Haninge', 'https://www.stff.se/rs/foreningar/ifk-haninge/11529/', true),
  ('IFK Lidingö BK', 'Stockholm', 'Lidingö', 'https://www.stff.se/rs/foreningar/ifk-lidingo-bk/12807/', true),
  ('IFK Lidingö FK', 'Stockholm', 'Lidingö', 'https://www.stff.se/rs/foreningar/ifk-lidingo-fk/8255/', true),
  ('IFK Sollentuna', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/ifk-sollentuna/10967/', true),
  ('IFK Stockholm FK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ifk-stockholm-fk/12940/', true),
  ('IFK Stocksund', 'Stockholm', 'Danderyd', 'https://www.stff.se/rs/foreningar/ifk-stocksund/11973/', true),
  ('IFK Tumba FK', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/ifk-tumba-fk/7790/', true),
  ('IFK Vaxholm', 'Stockholm', 'Vaxholm', 'https://www.stff.se/rs/foreningar/ifk-vaxholm/8402/', true),
  ('IFK Viksjö', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/ifk-viksjo/8443/', true),
  ('IK Allmänningen', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ik-allmanningen-/14768/', true),
  ('IK Frej Talangfotbollsförening', 'Stockholm', 'Täby', 'https://www.stff.se/rs/foreningar/ik-frej-talangfotbollsforening-/12379/', true),
  ('IK Frej Täby FF', 'Stockholm', 'Täby', 'https://www.stff.se/rs/foreningar/ik-frej-taby-ff/13076/', true),
  ('IK Hephata', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ik-hephata/12003/', true),
  ('IK Makkabi', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ik-makkabi/10671/', true),
  ('IK Sture', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ik-sture/10190/', true),
  ('IK Säbysjön', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/ik-sabysjon/8000/', true),
  ('Ingarö IF', 'Stockholm', 'Värmdö', 'https://www.stff.se/rs/foreningar/ingaro-if/10928/', true),
  ('Jarlabergs IF', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/jarlabergs-if/7457/', true),
  ('Jeberti United FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/jeberti-united-fc-/14800/', true),
  ('Joga Bonito IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/joga-bonito-if-/14744/', true),
  ('Johanneshovs FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/johanneshovs-ff/13604/', true),
  ('Järfälla AIF', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/jarfalla-aif/13631/', true),
  ('Järfälla FF', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/jarfalla-ff/12229/', true),
  ('Järfälla FF Academy', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/jarfalla-ff-academy-/13700/', true),
  ('Järfälla United IF', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/jarfalla-united-if-/14843/', true),
  ('Järla IF FK', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/jarla-if-fk/7621/', true),
  ('Järva IKF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/jarva-ikf/13652/', true),
  ('Kallhälls FF', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/kallhalls-ff/7958/', true),
  ('Karamardha UUF', 'Stockholm', 'Järfälla', 'https://www.stff.se/rs/foreningar/karamardha-uuf/14821/', true),
  ('Karlbergs BK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/karlbergs-bk/10871/', true),
  ('KIF Söderort', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/kif-soderort/11340/', true),
  ('Kilimanjaro FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/kilimanjaro-ff/13376/', true),
  ('Kista SC KFUM', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/kista-sc-kfum/10890/', true),
  ('Kofkella Kultur o IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/kofkella-kultur-o-if/8209/', true),
  ('Konglig Samhällsbyggnadssektion FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/konglig-samhallsbyggnadssektion-fc/12915/', true),
  ('Konyaspor Kultur och IF', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/konyaspor-kultur-och-if/8003/', true),
  ('Korpen Stockholms Motionsidrottsförening', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/korpen-stockholms-motionsidrottsforening/12233/', true),
  ('Kransen United FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/kransen-united-ff/11895/', true),
  ('Kronobergs BK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/kronobergs-bk/8988/', true),
  ('Kulturelitens FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/kulturelitens-ff/12412/', true),
  ('Kungsholmen United FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/kungsholmen-united-ff-/13685/', true),
  ('Kungsholmens Folkfotbollsförening', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/kungsholmens-folkfotbollsforening/13125/', true),
  ('Kungsängens IF', 'Stockholm', 'Upplands-Bro', 'https://www.stff.se/rs/foreningar/kungsangens-if/10798/', true),
  ('Kälvesta IoF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/kalvesta-iof/7540/', true),
  ('Kärrdal Bollklubb', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/karrdal-bollklubb-/14728/', true),
  ('Lado Sur FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/lado-sur-fc/13363/', true),
  ('Lidingö Gazoliners FC', 'Stockholm', 'Lidingö', 'https://www.stff.se/rs/foreningar/lidingo-gazoliners-fc/11867/', true),
  ('Lidingö Spartans FC', 'Stockholm', 'Lidingö', 'https://www.stff.se/rs/foreningar/lidingo-spartans-fc-/13692/', true),
  ('Lindhagen FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/lindhagen-ff/12789/', true),
  ('Ljungbackens IF', 'Stockholm', 'Lidingö', 'https://www.stff.se/rs/foreningar/ljungbackens-if/6724/', true),
  ('Ljungbackens IF Ungdomsfotboll', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ljungbackens-if-ungdomsfotboll-/14772/', true),
  ('Ljusterö IS', 'Stockholm', 'Österåker', 'https://www.stff.se/rs/foreningar/ljustero-is/12089/', true),
  ('Los Copihues IF', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/los-copihues-if/8977/', true),
  ('Långholmen FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/langholmen-fc/6892/', true),
  ('Maj FC', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/maj-fc/13287/', true),
  ('Mariebergs SK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/mariebergs-sk/10654/', true),
  ('Marockanska FC', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/marockanska-fc/13021/', true),
  ('Munsö IF', 'Stockholm', 'Ekerö', 'https://www.stff.se/rs/foreningar/munso-if/10609/', true),
  ('Mälarhöjden-Hägersten FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/malarhojden-hagersten-ff/13101/', true),
  ('Mälarhöjdens BK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/malarhojdens-bk/14762/', true),
  ('Mälarhöjdens IK Fotboll', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/malarhojdens-ik-fotboll/12911/', true),
  ('Mörtnäs IF', 'Stockholm', 'Värmdö', 'https://www.stff.se/rs/foreningar/mortnas-if/7332/', true),
  ('Nacka FC', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/nacka-fc/12853/', true),
  ('Nackdala AIS', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/nackdala-ais/8967/', true),
  ('Newroz FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/newroz-fc/12010/', true),
  ('Newroz FC AB', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/newroz-fc-ab/13485/', true),
  ('Nockebyhovs IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/nockebyhovs-if/6948/', true),
  ('Nordljus FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/nordljus-fc/14778/', true),
  ('Norrtulls SK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/norrtulls-sk/10543/', true),
  ('Norsborg FC', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/norsborg-fc-/13161/', true),
  ('Norsborgs IF', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/norsborgs-if/10541/', true),
  ('Nynäshamns IF FK', 'Stockholm', 'Nynäshamn', 'https://www.stff.se/rs/foreningar/nynashamns-if-fk/8033/', true),
  ('Olympique Nacka FC', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/olympique-nacka-fc-/14727/', true),
  ('Oracle''s Blues FF', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/oracles-blues-ff/13612/', true),
  ('Oranje FK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/oranje-fk/7070/', true),
  ('Oromo Stockholm IK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/oromo-stockholm-ik/13551/', true),
  ('Parsian IF', 'Stockholm', 'Upplands Väsby', 'https://www.stff.se/rs/foreningar/parsian-if/12638/', true),
  ('Polonia Falcons FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/polonia-falcons-ff/12070/', true),
  ('Preben BoIS', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/preben-bois/12183/', true),
  ('Qaran IKF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/qaran-ikf/12475/', true),
  ('Racket IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/racket-if/14780/', true),
  ('Real Väsby FC', 'Stockholm', 'Upplands Väsby', 'https://www.stff.se/rs/foreningar/real-vasby-fc/14754/', true),
  ('Redbrick City FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/redbrick-city-fc-/14801/', true),
  ('Reymersholms FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/reymersholms-ff/13451/', true),
  ('Reymersholms IK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/reymersholms-ik/10438/', true),
  ('Rinkeby Bussenhus IK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/rinkeby-bussenhus-ik/14747/', true),
  ('Rinkeby city FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/rinkeby-city-ff/14781/', true),
  ('Rinkeby United FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/rinkeby-united-fc/12532/', true),
  ('Rissne IF', 'Stockholm', 'Sundbyberg', 'https://www.stff.se/rs/foreningar/rissne-if/8947/', true),
  ('Roslags-Kulla IF', 'Stockholm', 'Österåker', 'https://www.stff.se/rs/foreningar/roslags-kulla-if/8945/', true),
  ('Rotebro IS FF', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/rotebro-is-ff/10422/', true),
  ('Runby IF', 'Stockholm', 'Upplands Väsby', 'https://www.stff.se/rs/foreningar/runby-if/10417/', true),
  ('Rydbo IF', 'Stockholm', 'Österåker', 'https://www.stff.se/rs/foreningar/rydbo-if/10409/', true),
  ('Rågsveds IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ragsveds-if/10396/', true),
  ('Råsunda FC', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/rasunda-fc/11811/', true),
  ('Råsunda IS', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/rasunda-is/10393/', true),
  ('RödaMarkerna IF', 'Stockholm', 'Upplands Väsby', 'https://www.stff.se/rs/foreningar/rodamarkerna-if/13329/', true),
  ('Rönninge Salem Fotboll', 'Stockholm', 'Salem', 'https://www.stff.se/rs/foreningar/ronninge-salem-fotboll/8142/', true),
  ('Saltsjö-Boo IF', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/saltsjo-boo-if/12667/', true),
  ('Saltsjöbadens IF', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/saltsjobadens-if/10370/', true),
  ('Segeltorps IF Fotboll', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/segeltorps-if-fotboll-/13623/', true),
  ('Sickla IF', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/sickla-if/11612/', true),
  ('Sjöstaden IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/sjostaden-if/13693/', true),
  ('Skarpnäck FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/skarpnack-ff/12091/', true),
  ('Skogås-Trångsunds FF', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/skogas-trangsunds-ff/7643/', true),
  ('Skå IK & Bygdegård', 'Stockholm', 'Ekerö', 'https://www.stff.se/rs/foreningar/ska-ik--bygdegard/12408/', true),
  ('Sköndals IK FK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/skondals-ik-fk/12895/', true),
  ('Solberga BK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/solberga-bk/10270/', true),
  ('Sollentuna FK', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/sollentuna-fk/7184/', true),
  ('Sollentuna Star FC', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/sollentuna-star-fc-/14792/', true),
  ('Sollentuna Utveckling FK', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/sollentuna-utveckling-fk-/13539/', true),
  ('Solna FC', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/solna-fc/12451/', true),
  ('Som United Fotbollsförening', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/som-united-fotbollsforening/12637/', true),
  ('Somaliska KoIF', 'Stockholm', 'Upplands-Bro', 'https://www.stff.se/rs/foreningar/somaliska-koif/13513/', true),
  ('Sorunda IF', 'Stockholm', 'Nynäshamn', 'https://www.stff.se/rs/foreningar/sorunda-if/10262/', true),
  ('Spartak Trollbäcken FC', 'Stockholm', 'Tyresö', 'https://www.stff.se/rs/foreningar/spartak-trollbacken-fc/13699/', true),
  ('Sporting FC Sollentuna', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/sporting-fc-sollentuna/13670/', true),
  ('Spånga IS FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/spanga-is-ff/12494/', true),
  ('Spånga IS FK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/spanga-is-fk/7892/', true),
  ('Spårvägens FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/sparvagens-ff/7864/', true),
  ('Stockholm Akademisk FK', 'Stockholm', 'Haninge', 'https://www.stff.se/rs/foreningar/stockholm-akademisk-fk/14757/', true),
  ('Stockholm Craft BC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/stockholm-craft-bc/13331/', true),
  ('Stockholm Cranes IF', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/stockholm-cranes-if/13060/', true),
  ('Stockholm Framefotboll IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/stockholm-framefotboll-if-/13576/', true),
  ('Stockholm StreetSoccer FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/stockholm-streetsoccer-ff-/13348/', true),
  ('Stockholm Södra FF', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/stockholm-sodra-ff/12675/', true),
  ('Stockholm United FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/stockholm-united-fc-/13715/', true),
  ('Stockholms Universitets FF', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/stockholms-universitets-ff/13071/', true),
  ('Stocksunds IF', 'Stockholm', 'Danderyd', 'https://www.stff.se/rs/foreningar/stocksunds-if/10217/', true),
  ('Storskogens SK', 'Stockholm', 'Sundbyberg', 'https://www.stff.se/rs/foreningar/storskogens-sk/10203/', true),
  ('Stureby FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/stureby-ff/11789/', true),
  ('Stureby SK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/stureby-sk/10189/', true),
  ('Stuvsta FF', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/stuvsta-ff/7268/', true),
  ('Stuvsta IF', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/stuvsta-if/8931/', true),
  ('Style United FC', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/style-united-fc-/13682/', true),
  ('Sundbyberg FC', 'Stockholm', 'Sundbyberg', 'https://www.stff.se/rs/foreningar/sundbyberg-fc/7108/', true),
  ('Sundbybergs IK', 'Stockholm', 'Sundbyberg', 'https://www.stff.se/rs/foreningar/sundbybergs-ik/10175/', true),
  ('Suryoye United FC', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/suryoye-united-fc/14782/', true),
  ('Svensk-Palestinska FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/svensk-palestinska-ff/12628/', true),
  ('Syrianska Tensta IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/syrianska-tensta-if-/6870/', true),
  ('Sätra SK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/satra-sk/8927/', true),
  ('Söder Futsalklubb', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/soder-futsalklubb/12538/', true),
  ('Sörskogens IF', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/sorskogens-if/10113/', true),
  ('Tallkrogens IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/tallkrogens-if/10107/', true),
  ('Tekniska Högskolan FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/tekniska-hogskolan-fc/12535/', true),
  ('Tian United FC', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/tian-united-fc-/13594/', true),
  ('Top FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/top-fc/12526/', true),
  ('Topkapi FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/topkapi-ff-/13597/', true),
  ('Trissans idrottsförening', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/trissans-idrottsforening-/14799/', true),
  ('Tudor Arms FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/tudor-arms-fc/8918/', true),
  ('Tullinge BK', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/tullinge-bk/7829/', true),
  ('Tullinge FF', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/tullinge-ff/7125/', true),
  ('Tullinge Triangel Pojkar FK', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/tullinge-triangel-pojkar-fk/6759/', true),
  ('Tullingebollen IF', 'Stockholm', 'Botkyrka', 'https://www.stff.se/rs/foreningar/tullingebollen-if-/13628/', true),
  ('Tungelsta IF', 'Stockholm', 'Haninge', 'https://www.stff.se/rs/foreningar/tungelsta-if/10037/', true),
  ('Tureberg FF United', 'Stockholm', 'Sollentuna', 'https://www.stff.se/rs/foreningar/tureberg-ff-united-/14794/', true),
  ('Tyresö FF', 'Stockholm', 'Tyresö', 'https://www.stff.se/rs/foreningar/tyreso-ff/8914/', true),
  ('Tyresö IF', 'Stockholm', 'Tyresö', 'https://www.stff.se/rs/foreningar/tyreso-if-/14733/', true),
  ('Tyresö Strand FC', 'Stockholm', 'Tyresö', 'https://www.stff.se/rs/foreningar/tyreso-strand-fc-/13480/', true),
  ('Täby FK', 'Stockholm', 'Täby', 'https://www.stff.se/rs/foreningar/taby-fk/12549/', true),
  ('Täby FK Utveckling', 'Stockholm', 'Täby', 'https://www.stff.se/rs/foreningar/taby-fk-utveckling-/14803/', true),
  ('Täby Idrottsförening', 'Stockholm', 'Täby', 'https://www.stff.se/rs/foreningar/taby-idrottsforening-/13335/', true),
  ('Upplands-Bro United FK', 'Stockholm', 'Upplands-Bro', 'https://www.stff.se/rs/foreningar/upplands-bro-united-fk/13053/', true),
  ('Ursvik IK', 'Stockholm', 'Sundbyberg', 'https://www.stff.se/rs/foreningar/ursvik-ik/9985/', true),
  ('Ursvik IK FF', 'Stockholm', 'Sundbyberg', 'https://www.stff.se/rs/foreningar/ursvik-ik-ff-/14766/', true),
  ('Uruguayanska FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/uruguayanska-ff/12470/', true),
  ('Vallentuna BK', 'Stockholm', 'Vallentuna', 'https://www.stff.se/rs/foreningar/vallentuna-bk/9973/', true),
  ('Vasalund FF', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/vasalund-ff/11838/', true),
  ('Vasalund Fotboll AB', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/vasalund-fotboll-ab/13297/', true),
  ('Vasalund IF', 'Stockholm', 'Solna', 'https://www.stff.se/rs/foreningar/vasalund-if/9959/', true),
  ('Vasalund Stockholm IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/vasalund-stockholm-if/7474/', true),
  ('Vasastans BK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/vasastans-bk/6800/', true),
  ('Vaxö AIF', 'Stockholm', 'Vaxholm', 'https://www.stff.se/rs/foreningar/vaxo-aif/13311/', true),
  ('Vega FC', 'Stockholm', 'Haninge', 'https://www.stff.se/rs/foreningar/vega-fc/12976/', true),
  ('Vendelsö IK', 'Stockholm', 'Haninge', 'https://www.stff.se/rs/foreningar/vendelso-ik/9945/', true),
  ('Viggbyholms IK FF', 'Stockholm', 'Täby', 'https://www.stff.se/rs/foreningar/viggbyholms-ik-ff/12694/', true),
  ('Viña del Mar IF', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/vina-del-mar-if/13304/', true),
  ('Vistaberg IF', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/vistaberg-if/13558/', true),
  ('Vårby United FC', 'Stockholm', 'Huddinge', 'https://www.stff.se/rs/foreningar/varby-united-fc-/14730/', true),
  ('Vällingby AIK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/vallingby-aik/9875/', true),
  ('Värmdö IF', 'Stockholm', 'Värmdö', 'https://www.stff.se/rs/foreningar/varmdo-if/9869/', true),
  ('Värtans IK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/vartans-ik/9866/', true),
  ('Väsby FF', 'Stockholm', 'Upplands Väsby', 'https://www.stff.se/rs/foreningar/vasby-ff/13230/', true),
  ('Västerhaninge IF', 'Stockholm', 'Haninge', 'https://www.stff.se/rs/foreningar/vasterhaninge-if/9859/', true),
  ('Västertorps BK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/vastertorps-bk/8905/', true),
  ('Westermalms IF FK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/westermalms-if-fk/7306/', true),
  ('Wollmars FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/wollmars-ff/12071/', true),
  ('Yenaris FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/yenaris-ff/13469/', true),
  ('Åkersberga FC', 'Stockholm', 'Österåker', 'https://www.stff.se/rs/foreningar/akersberga-fc/12855/', true),
  ('Åkeshovs Idrott och FK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/akeshovs-idrott-och-fk/9821/', true),
  ('Årsta FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/arsta-ff/12299/', true),
  ('Älta IF', 'Stockholm', 'Nacka', 'https://www.stff.se/rs/foreningar/alta-if/9790/', true),
  ('Älvsjö AIK DFF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/alvsjo-aik-dff/13512/', true),
  ('Älvsjö AIK FF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/alvsjo-aik-ff/7708/', true),
  ('Ängby IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/angby-if/9781/', true),
  ('Äppelvikens SK', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/appelvikens-sk-/13681/', true),
  ('Örby IS', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/orby-is/9763/', true),
  ('Örnarna IF', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ornarna-if/12166/', true),
  ('Ösmo GIF FK', 'Stockholm', 'Nynäshamn', 'https://www.stff.se/rs/foreningar/osmo-gif-fk/7867/', true),
  ('Östberga City FC', 'Stockholm', 'Stockholm', 'https://www.stff.se/rs/foreningar/ostberga-city-fc-/13349/', true),
  ('Österåker United BK', 'Stockholm', 'Österåker', 'https://www.stff.se/rs/foreningar/osteraker-united-bk/8901/', true),
  ('Österåker United FK', 'Stockholm', 'Österåker', 'https://www.stff.se/rs/foreningar/osteraker-united-fk/8269/', true)
on conflict (name, region) do update set
  municipality = excluded.municipality,
  website = excluded.website,
  verified = true,
  updated_at = now();

commit;

select count(*) as stff_stockholm_clubs
from public.clubs
where region = 'Stockholm'
  and website like 'https://www.stff.se/rs/foreningar/%';
